---
services:
  postfix:
    image: boky/postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
    ports:
      - "1587:587"
    networks:
      - mailnet
  python:
    image: python:3.12-slim
    command: ["python", "/scripts/send_email.py"]
    environment:
      - SENDER_EMAIL=${SENDER_EMAIL}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - ./scripts:/scripts
    networks:
      - mailnet
    depends_on:
      - postfix
networks:
  mailnet:
    driver: bridge
